import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Calendar, Clock, MapPin, User, Plus, Download, Eye, X, FileText } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { toast } from 'sonner';

const AppointmentsModule = () => {
  const navigate = useNavigate();
  const [selectedReport, setSelectedReport] = useState(null);

  // Mock Data
  const appointments = [
    { 
      id: 1, 
      doctor: 'Dr. Sarah Smith', 
      type: 'Dental Checkup', 
      date: '2025-10-24', 
      time: '10:00 AM', 
      status: 'Upcoming',
      notes: 'Regular 6-month checkup.' 
    },
    { 
      id: 2, 
      doctor: 'Dr. John Doe', 
      type: 'Root Canal', 
      date: '2025-09-15', 
      time: '02:30 PM', 
      status: 'Completed',
      reportData: {
        diagnosis: 'Infected pulp in tooth #14',
        treatment: 'Root Canal Therapy performed under local anesthesia.',
        prescription: 'Amoxicillin 500mg, Ibuprofen 400mg',
        nextVisit: 'Crown placement in 2 weeks.'
      }
    },
  ];

  // --- 1. DOWNLOAD FUNCTIONALITY ---
  const handleDownload = (apt) => {
    // Create a mock report content
    const reportContent = `
    CARE CONNECT MEDICAL REPORT
    ---------------------------
    Date: ${apt.date}
    Doctor: ${apt.doctor}
    Service: ${apt.type}
    
    DIAGNOSIS:
    ${apt.reportData?.diagnosis || 'Routine Checkup - No issues found.'}
    
    TREATMENT:
    ${apt.reportData?.treatment || 'Cleaning and Polishing'}
    
    PRESCRIPTION:
    ${apt.reportData?.prescription || 'None'}
    
    ---------------------------
    Generated by Care Connect System
    `;

    // Create a Blob (file) from the text
    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    
    // Create a temporary link to trigger download
    const link = document.createElement('a');
    link.href = url;
    link.download = `Report_${apt.type.replace(/\s+/g, '_')}_${apt.date}.txt`;
    document.body.appendChild(link);
    link.click();
    
    // Cleanup
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);
    
    toast.success("Report downloaded successfully");
  };

  return (
    <div className="space-y-6 relative">
      {/* Header with Action Button */}
      <div className="flex justify-between items-center">
        <h2 className="text-2xl font-bold text-gray-900">My Appointments</h2>
        <button 
          onClick={() => navigate('/book-appointment')}
          className="bg-[#13c5dd] text-white px-5 py-2.5 rounded-xl text-sm font-bold hover:bg-[#0fb3ca] transition-all shadow-lg shadow-[#13c5dd]/20 hover:shadow-xl hover:-translate-y-0.5 flex items-center gap-2"
        >
          <Plus size={18} />
          Book New
        </button>
      </div>

      {/* Appointment List */}
      <div className="grid gap-4">
        {appointments.length > 0 ? (
          appointments.map((apt) => (
            <div 
              key={apt.id} 
              className="bg-white p-6 rounded-2xl shadow-sm border border-gray-100 flex flex-col md:flex-row md:items-center justify-between gap-6 transition-all hover:shadow-md"
            >
              {/* Left Side: Info */}
              <div className="flex items-start gap-4">
                {/* Date Badge */}
                <div className="w-16 h-16 rounded-2xl bg-[#13c5dd]/10 text-[#13c5dd] flex flex-col items-center justify-center font-bold border border-[#13c5dd]/20 flex-shrink-0">
                  <span className="text-xl leading-none">{apt.date.split('-')[2]}</span>
                  <span className="text-[10px] uppercase font-medium mt-1">
                    {new Date(apt.date).toLocaleString('default', { month: 'short' })}
                  </span>
                </div>

                {/* Details */}
                <div>
                  <h4 className="font-bold text-lg text-gray-900">{apt.type}</h4>
                  <div className="flex flex-col sm:flex-row sm:items-center gap-1 sm:gap-4 mt-1 text-sm text-gray-500">
                    <div className="flex items-center gap-1.5">
                      <User size={14} className="text-[#13c5dd]" /> 
                      {apt.doctor}
                    </div>
                    <div className="hidden sm:block w-1 h-1 rounded-full bg-gray-300" />
                    <div className="flex items-center gap-1.5">
                      <Clock size={14} className="text-[#13c5dd]" /> 
                      {apt.time}
                    </div>
                  </div>
                </div>
              </div>
              
              {/* Right Side: Status & Actions */}
              <div className="flex flex-col md:flex-row items-start md:items-center gap-4">
                <span className={`px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wider ${
                  apt.status === 'Upcoming' 
                    ? 'bg-blue-50 text-blue-600 border border-blue-100' 
                    : 'bg-green-50 text-green-600 border border-green-100'
                }`}>
                  {apt.status}
                </span>

                {/* ACTIONS (Only for Completed Appointments) */}
                {apt.status === 'Completed' && (
                  <div className="flex gap-2">
                    <button 
                      onClick={() => setSelectedReport(apt)}
                      className="p-2 text-gray-500 hover:text-[#13c5dd] hover:bg-[#13c5dd]/10 rounded-lg transition-colors tooltip"
                      title="View Report"
                    >
                      <Eye size={18} />
                    </button>
                    <button 
                      onClick={() => handleDownload(apt)}
                      className="p-2 text-gray-500 hover:text-[#13c5dd] hover:bg-[#13c5dd]/10 rounded-lg transition-colors tooltip"
                      title="Download Report"
                    >
                      <Download size={18} />
                    </button>
                  </div>
                )}
              </div>
            </div>
          ))
        ) : (
          <div className="text-center py-12 bg-white rounded-2xl border border-dashed border-gray-200">
            <p className="text-gray-400">No appointments found.</p>
          </div>
        )}
      </div>

      {/* --- 2. REPORT MODAL --- */}
      <AnimatePresence>
        {selectedReport && (
          <>
            {/* Backdrop */}
            <motion.div 
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={() => setSelectedReport(null)}
              className="fixed inset-0 bg-black/40 backdrop-blur-sm z-[60]"
            />
            
            {/* Modal */}
            <div className="fixed inset-0 z-[70] flex items-center justify-center p-4 pointer-events-none">
              <motion.div 
                initial={{ opacity: 0, scale: 0.95, y: 20 }}
                animate={{ opacity: 1, scale: 1, y: 0 }}
                exit={{ opacity: 0, scale: 0.95, y: 20 }}
                className="bg-white rounded-2xl shadow-2xl w-full max-w-lg overflow-hidden pointer-events-auto"
              >
                {/* Modal Header */}
                <div className="bg-[#13c5dd] p-6 text-white flex justify-between items-start">
                  <div>
                    <h3 className="text-xl font-bold flex items-center gap-2">
                      <FileText size={20} /> Medical Report
                    </h3>
                    <p className="text-[#13c5dd]-100 text-sm mt-1 opacity-90">
                      ID: #{selectedReport.id.toString().padStart(6, '0')}
                    </p>
                  </div>
                  <button 
                    onClick={() => setSelectedReport(null)}
                    className="p-1 hover:bg-white/20 rounded-full transition-colors"
                  >
                    <X size={20} />
                  </button>
                </div>

                {/* Modal Content */}
                <div className="p-6 space-y-6">
                  <div className="grid grid-cols-2 gap-4 pb-6 border-b border-gray-100">
                    <div>
                      <p className="text-xs text-gray-400 uppercase font-bold">Doctor</p>
                      <p className="font-medium text-gray-900">{selectedReport.doctor}</p>
                    </div>
                    <div>
                      <p className="text-xs text-gray-400 uppercase font-bold">Date</p>
                      <p className="font-medium text-gray-900">{selectedReport.date}</p>
                    </div>
                  </div>

                  <div className="space-y-4">
                    <div>
                      <p className="text-xs text-[#13c5dd] uppercase font-bold mb-1">Diagnosis</p>
                      <p className="text-gray-700 bg-gray-50 p-3 rounded-lg text-sm leading-relaxed">
                        {selectedReport.reportData?.diagnosis || "Routine checkup completed successfully."}
                      </p>
                    </div>
                    
                    <div>
                      <p className="text-xs text-[#13c5dd] uppercase font-bold mb-1">Treatment Plan</p>
                      <p className="text-gray-700 bg-gray-50 p-3 rounded-lg text-sm leading-relaxed">
                        {selectedReport.reportData?.treatment || "N/A"}
                      </p>
                    </div>
                  </div>

                  <div className="pt-4 flex gap-3">
                    <button 
                      onClick={() => handleDownload(selectedReport)}
                      className="flex-1 bg-[#13c5dd] text-white py-3 rounded-xl font-bold text-sm hover:bg-[#0fb3ca] transition-colors flex items-center justify-center gap-2"
                    >
                      <Download size={16} /> Download PDF
                    </button>
                    <button 
                      onClick={() => setSelectedReport(null)}
                      className="flex-1 bg-gray-100 text-gray-700 py-3 rounded-xl font-bold text-sm hover:bg-gray-200 transition-colors"
                    >
                      Close
                    </button>
                  </div>
                </div>
              </motion.div>
            </div>
          </>
        )}
      </AnimatePresence>
    </div>
  );
};

export default AppointmentsModule;